export const adminLabEndpoints = {
  biomarkers: "admin/labs/biomarkers/",
  biomarkerSync: "admin/labs/biomarkers/sync/",
  catalogLabs: "admin/labs/catalog/labs/",
  catalogItems: "admin/labs/catalog/items/",
  catalogItemDetail: (id: string) => `admin/labs/catalog/items/${id}/`,
  panels: "admin/labs/panels/",
  panelFromCatalog: "admin/labs/panels/from-catalog/",
  panelDetail: (id: string) => `admin/labs/panels/${id}/`,
  panelStatus: (id: string) => `admin/labs/panels/${id}/check-junction-status/`,
  panelClients: (id: string) => `admin/labs/panels/${id}/clients/`,
  assignmentSubmit: (id: string) => `admin/labs/assignments/${id}/submit-to-junction/`,
  assignmentSync: (id: string) => `admin/labs/assignments/${id}/sync-to-tenant/`,
  assignmentStatus: (id: string) => `admin/labs/assignments/${id}/check-junction-status/`,
  assignmentReplace: (id: string) => `admin/labs/assignments/${id}/replace-submission/`,
  combinedPanels: "admin/labs/combined-panels/",
  combinedPanelDetail: (id: string) => `admin/labs/combined-panels/${id}/`,
  combinedValidate: "admin/labs/combined-panels/validate/",
  combinedClients: (id: string) => `admin/labs/combined-panels/${id}/clients/`,
  panelChangeHistory: (id: string) => `admin/labs/panels/${id}/change-history/`,
  orders: "admin/labs/orders/",
  orderResults: (id: string) => `admin/labs/orders/${id}/results/`,
  orderManualUpdate: (id: string) => `admin/labs/orders/${id}/manual-update/`,
  orderResultPdf: (id: string) => `admin/labs/orders/${id}/result-pdf/`,
  orderRequisitionPdf: (id: string) => `admin/labs/orders/${id}/requisition-pdf/`,
  orderCollectionInstructionsPdf: (id: string) => `admin/labs/orders/${id}/collection-instructions-pdf/`,
};
