import { BookOpen, Check, Clock3, LockKeyhole, ShieldCheck } from "lucide-react";
import { employeeCorporateFixture } from "./fixtures";

const gates = [
  { number: 0, title: "Get oriented", description: "Program education and consent", state: "current", icon: BookOpen },
  { number: 1, title: "Complete intake", description: "Program-specific questionnaire", state: "locked", icon: Clock3 },
  { number: 2, title: "Clinical review", description: "Care access after approval", state: "locked", icon: ShieldCheck },
] as const;

export default function MyProgram() {
  const program = employeeCorporateFixture.program;
  return <div className="space-y-6">
    <div><div className="mb-2 flex items-center gap-2"><span className="rounded-full bg-blue-100 px-2.5 py-1 text-xs font-semibold text-blue-700">Pilot preview</span><span className="rounded-full border px-2.5 py-1 text-xs text-slate-600">Assigned program only</span></div><h1 className="text-3xl font-semibold tracking-tight">My Program</h1><p className="mt-1 text-sm text-slate-500">Your employer-sponsored health journey and next steps.</p></div>
    <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="bg-gradient-to-r from-blue-700 to-indigo-700 p-6 text-white sm:p-8"><p className="text-xs font-semibold uppercase tracking-widest text-blue-100">{program.employerName}</p><h2 className="mt-2 text-2xl font-semibold">{program.name}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-blue-50">{program.description}</p></div><div className="flex flex-col justify-between gap-4 p-5 sm:flex-row sm:items-center sm:p-6"><div><p className="text-sm font-medium text-slate-900">Next: Gate 0 orientation</p><p className="mt-1 text-xs text-slate-500">The enrollment connection will activate this step during Day 2.</p></div><button disabled aria-disabled="true" className="rounded-lg bg-slate-200 px-5 py-2.5 text-sm font-semibold text-slate-500">Begin Gate 0 — Day 2</button></div></section>
    <section className="rounded-2xl border bg-white p-5 shadow-sm sm:p-6"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-lg font-semibold">Program progress</h2><p className="text-sm text-slate-500">Gate visibility only; no clinical details are shown.</p></div><LockKeyhole className="h-5 w-5 text-slate-400" /></div><div className="grid gap-4 md:grid-cols-3">{gates.map(({ number, title, description, state, icon: Icon }) => <div key={number} className={`rounded-xl border p-4 ${state === "current" ? "border-blue-300 bg-blue-50" : "bg-slate-50"}`}><div className="flex items-center justify-between"><span className={`flex h-9 w-9 items-center justify-center rounded-full ${state === "current" ? "bg-blue-700 text-white" : "bg-slate-200 text-slate-500"}`}><Icon className="h-4 w-4" /></span>{state === "current" ? <span className="rounded-full bg-blue-100 px-2 py-1 text-[10px] font-semibold uppercase text-blue-700">Current</span> : <LockKeyhole className="h-4 w-4 text-slate-400" />}</div><p className="mt-4 text-xs font-semibold uppercase tracking-wide text-slate-500">Gate {number}</p><h3 className="mt-1 font-semibold">{title}</h3><p className="mt-1 text-sm text-slate-500">{description}</p></div>)}</div></section>
    <section className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border bg-white p-5"><BookOpen className="h-5 w-5 text-blue-700" /><h2 className="mt-3 font-semibold">Education</h2><p className="mt-1 text-sm text-slate-500">Program learning content will appear here after enrollment is connected.</p><button disabled className="mt-4 text-sm font-semibold text-slate-400">Coming Day 2</button></div><div className="rounded-2xl border bg-white p-5"><Check className="h-5 w-5 text-emerald-700" /><h2 className="mt-3 font-semibold">Personal compliance</h2><p className="mt-1 text-sm text-slate-500">Track your own non-clinical program requirements without employer access to medical details.</p><button disabled className="mt-4 text-sm font-semibold text-slate-400">Coming Day 2</button></div></section>
  </div>;
}
