import { useEffect, useState } from "react";
import { BookOpen, Check, Clock3, Loader2, LockKeyhole, PlayCircle, RefreshCw, ShieldCheck } from "lucide-react";
import { useLocation } from "react-router-dom";
import type { EmployeeCorporateContext } from "./contracts";
import { fetchAssignedProgram, getCachedAssignedProgram, setPilotGate } from "./corporateApi";

const gateIcon = (number: number) => number === 0 ? BookOpen : number === 1 ? Clock3 : ShieldCheck;

export default function MyProgram() {
  const location = useLocation();
  const [context, setContext] = useState<EmployeeCorporateContext | null>(() => getCachedAssignedProgram());
  const [loading, setLoading] = useState(() => !getCachedAssignedProgram());
  const [error, setError] = useState("");
  const [advancing, setAdvancing] = useState(false);
  const load = async (force = false) => { if (!context) setLoading(true); setError(""); try { setContext(await fetchAssignedProgram({ force })); } catch (reason: any) { setError(reason?.response?.data?.message || reason?.response?.data?.detail || reason?.message || (typeof reason?.error === "string" ? reason.error : reason?.error?.message) || "Your assigned program could not be loaded."); } finally { setLoading(false); } };
  useEffect(() => { void load(true); }, []);
  useEffect(() => {
    if (context && location.hash === "#orientation-modules") {
      requestAnimationFrame(() => document.getElementById("orientation-modules")?.scrollIntoView({ behavior: "smooth" }));
    }
  }, [context, location.hash]);
  const switchGate = async (targetGate: 0 | 1) => { setAdvancing(true); setError(""); try { await setPilotGate(targetGate); await load(true); } catch (reason: any) { setError(reason?.response?.data?.error || reason?.message || "The pilot gate could not be changed."); } finally { setAdvancing(false); } };
  if (loading) return <div className="flex min-h-[55vh] items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-blue-700" /></div>;
  if (!context) return <section className="mx-auto mt-12 max-w-xl rounded-2xl border bg-white p-8 text-center shadow-sm"><LockKeyhole className="mx-auto h-8 w-8 text-slate-400" /><h1 className="mt-4 text-xl font-semibold">Assigned program unavailable</h1><p className="mt-2 text-sm text-slate-500">{error}</p><button onClick={() => void load()} className="mt-5 inline-flex items-center rounded-lg border px-4 py-2 text-sm font-semibold"><RefreshCw className="mr-2 h-4 w-4" />Retry</button></section>;
  const { program, employer, enrollment, assigned_questionnaire } = context;
  const gateZero = enrollment.gate_progress.gate_0 || {};
  return <div className="space-y-6">
    <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><div className="mb-2 flex items-center gap-2"><span className="rounded-full bg-blue-100 px-2.5 py-1 text-xs font-semibold text-blue-700">Corporate pilot</span><span className="rounded-full border px-2.5 py-1 text-xs text-slate-600">Assigned program only</span></div><h1 className="text-3xl font-semibold tracking-tight">My Program</h1><p className="mt-1 text-sm text-slate-500">Your employer-sponsored health journey and next steps.</p></div><span className="w-fit rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-semibold text-emerald-700">{enrollment.status_label} enrollment</span></div>
    <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="bg-gradient-to-r from-blue-700 to-indigo-700 p-6 text-white sm:p-8"><p className="text-xs font-semibold uppercase tracking-widest text-blue-100">{employer.name}</p><h2 className="mt-2 text-2xl font-semibold">{program.name}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-blue-50">{program.description}</p></div><div className="flex flex-col justify-between gap-4 p-5 sm:flex-row sm:items-center sm:p-6"><div><p className="text-sm font-medium text-slate-900">Current: Gate {enrollment.current_gate} {context.gates.find((gate) => gate.number === enrollment.current_gate)?.name}</p><p className="mt-1 text-xs text-slate-500">Only this employer-assigned path is available. Open treatment discovery is blocked.</p></div>{enrollment.current_gate === 0 ? <button disabled={advancing} onClick={() => void switchGate(1)} className="rounded-lg bg-blue-700 px-5 py-2.5 text-sm font-semibold text-white hover:bg-blue-800 disabled:opacity-60">{advancing ? "Opening Gate 1…" : "Continue to Gate 1"}</button> : assigned_questionnaire.available && assigned_questionnaire.url ? <button onClick={() => window.location.assign(assigned_questionnaire.url as string)} className="rounded-lg bg-blue-700 px-5 py-2.5 text-sm font-semibold text-white hover:bg-blue-800">Open assigned questionnaire</button> : <span className="rounded-lg bg-slate-100 px-5 py-2.5 text-sm font-semibold text-slate-500">Questionnaire unavailable</span>}</div></section>
    <section className="rounded-2xl border bg-white p-5 shadow-sm sm:p-6"><div className="mb-5 flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="text-lg font-semibold">Program progress</h2><p className="text-sm text-slate-500">Personal gate visibility only; your employer sees aggregate counts.</p></div><div className="flex rounded-lg border bg-slate-50 p-1" aria-label="Pilot gate preview"><button disabled={advancing} onClick={() => void switchGate(0)} className={`rounded-md px-3 py-1.5 text-xs font-semibold ${enrollment.current_gate === 0 ? "bg-white text-blue-700 shadow-sm" : "text-slate-500"}`}>Preview Gate 0</button><button disabled={advancing} onClick={() => void switchGate(1)} className={`rounded-md px-3 py-1.5 text-xs font-semibold ${enrollment.current_gate === 1 ? "bg-white text-blue-700 shadow-sm" : "text-slate-500"}`}>Preview Gate 1</button></div></div><div className="grid gap-4 md:grid-cols-3">{context.gates.map((gate) => { const Icon = gateIcon(gate.number); const current = gate.number === enrollment.current_gate; const complete = gate.number < enrollment.current_gate; return <div key={gate.number} className={`rounded-xl border p-4 ${current ? "border-blue-300 bg-blue-50" : complete ? "border-emerald-200 bg-emerald-50" : "bg-slate-50"}`}><div className="flex items-center justify-between"><span className={`flex h-9 w-9 items-center justify-center rounded-full ${current ? "bg-blue-700 text-white" : complete ? "bg-emerald-600 text-white" : "bg-slate-200 text-slate-500"}`}><Icon className="h-4 w-4" /></span>{current ? <span className="rounded-full bg-blue-100 px-2 py-1 text-[10px] font-semibold uppercase text-blue-700">Current</span> : complete ? <Check className="h-4 w-4 text-emerald-600" /> : <LockKeyhole className="h-4 w-4 text-slate-400" />}</div><p className="mt-4 text-xs font-semibold uppercase tracking-wide text-slate-500">Gate {gate.number}</p><h3 className="mt-1 font-semibold">{gate.name}</h3><p className="mt-1 text-sm text-slate-500">{gate.description}</p></div>; })}</div></section>
    <section id="orientation-modules" className="rounded-2xl border bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-col justify-between gap-2 sm:flex-row sm:items-end"><div><h2 className="text-lg font-semibold">Gate 0 orientation</h2><p className="mt-1 text-sm text-slate-500">{gateZero.completed_modules || 0} of {gateZero.total_modules || program.orientation_modules.length} modules acknowledged</p></div><span className="text-xs font-semibold text-blue-700">Program-scoped content</span></div><div className="mt-5 grid gap-3 md:grid-cols-3">{program.orientation_modules.map((module, index) => <article key={module.id} className="rounded-xl border p-4"><div className="flex items-center justify-between"><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-semibold uppercase text-slate-600">{module.kind}</span>{index < (gateZero.completed_modules || 0) ? <Check className="h-4 w-4 text-emerald-600" /> : <PlayCircle className="h-4 w-4 text-blue-700" />}</div><h3 className="mt-3 text-sm font-semibold">{module.title}</h3><p className="mt-1 text-xs text-slate-500">About {module.minutes} minutes</p></article>)}</div></section>
    <section className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border bg-white p-5"><BookOpen className="h-5 w-5 text-blue-700" /><h2 className="mt-3 font-semibold">Assigned education only</h2><p className="mt-1 text-sm text-slate-500">Learning is limited to content attached to {program.name}.</p><span className="mt-4 inline-block text-sm font-semibold text-emerald-700">Gate 0 available</span></div><div className="rounded-2xl border bg-white p-5"><ShieldCheck className="h-5 w-5 text-slate-500" /><h2 className="mt-3 font-semibold">Clinical features</h2><p className="mt-1 text-sm text-slate-500">Appointments, prescriptions, labs, and records stay hidden until Gate 2 explicitly enables them.</p><span className="mt-4 inline-block text-sm font-semibold text-slate-400">{context.clinical_access_enabled ? "Gate 2 enabled" : "Locked by program gate"}</span></div></section>
  </div>;
}
