export const PRODUCT_CATEGORIES = [
  "Endomiphene", "Glutathione", "Injection Kit", "Methylcobalamin", "NAD+", "Orforglipron",
  "PT-141 - Men", "PT-141 - Women", "Semaglutide", "Sermorelin", "Sildenafil", "Syringe",
  "Tadalafil", "Tesamorelin", "Tirzepatide", "TRT", "Wegovy", "Zepbound", "Estradiol", "Progesterone",
];

export const DOSE_MAPPINGS = [
  { label: "Foundayo 0.8mg", category: "Orforglipron" },
  { label: "Glutathione", category: "Glutathione" },
  { label: "Glutathione 200mg", category: "Glutathione" },
  { label: "NAD+", category: "NAD+" },
  { label: "NAD+ 100mg", category: "NAD+" },
  { label: "NAD+ 250mg", category: "NAD+" },
  { label: "PT-141 - Men", category: "PT-141 - Men" },
  { label: "PT-141 - Women", category: "PT-141 - Women" },
  { label: "Semaglutide 0.2mg", category: "Semaglutide" },
  { label: "Semaglutide 0.2mg Microdosing", category: "Semaglutide" },
  { label: "Wegovy 0.25mg", category: "Semaglutide" },
  { label: "Wegovy 0.5mg", category: "Semaglutide" },
  { label: "Wegovy 1.0mg", category: "Semaglutide" },
  { label: "Sermorelin", category: "Sermorelin" },
  { label: "Sermorelin 3mg", category: "Sermorelin" },
  { label: "Sermorelin 5mg", category: "Sermorelin" },
  { label: "Sildenafil Citrate 20mg", category: "Sildenafil" },
  { label: "Sildenafil 20mg", category: "Sildenafil" },
  { label: "Sertraline 50mg", category: "Sertraline" },
  { label: "Sertraline 100mg", category: "Sertraline" },
  { label: "Tadalafil 2.5mg", category: "Tadalafil" },
  { label: "Tadalafil 5mg", category: "Tadalafil" },
  { label: "Tesamorelin", category: "Tesamorelin" },
  { label: "Tirzepatide 1.5mg", category: "Tirzepatide" },
  { label: "Tirzepatide 1.5mg Microdosing", category: "Tirzepatide" },
  { label: "Zepbound 2.5mg", category: "Tirzepatide" },
  { label: "Zepbound 5mg", category: "Tirzepatide" },
  { label: "TRT", category: "TRT" },
  { label: "Testosterone Cypionate 200mg", category: "TRT" },
  { label: "Enclomiphene 12.5mg", category: "Enclomiphene" },
  { label: "Estradiol 0.5mg", category: "Estradiol" },
  { label: "Estradiol 1.0mg", category: "Estradiol" },
  { label: "Progesterone 100mg", category: "Progesterone" },
];

export const TITRATION_CATEGORIES = ["Alternative Regimen", "Rapid Regimen", "Twice Weekly Regimen", "Standard", "Low Dose", "Normal Dose"];
