export const FLOWBUILDER_MODE_BY_COMPLEXITY = {
  overview: 350,
} as const;

export const FLOWBUILDER_OVERVIEW_EDGE_CAP = 260;
export const FLOWBUILDER_BENCHMARK_QUERY_PARAM = "fbBenchmark";
export const FLOWBUILDER_LAYOUT_CACHE_LIMIT = 20;
export const FLOWBUILDER_DEFERRED_INITIAL_LAYOUT_QUESTION_THRESHOLD = 90;
export const FLOWBUILDER_DEFERRED_INITIAL_LAYOUT_DELAY_MS = 40;
export const FLOWBUILDER_LAYOUT_EDGE_LIMIT = 320;
export const FLOWBUILDER_DEFERRED_LAYOUT_EDGE_LIMIT = 240;
export const FLOWBUILDER_AUTO_GROUPING_COMPLEXITY_THRESHOLD = 700;
export const FLOWBUILDER_LOW_ZOOM_EDGE_SIMPLIFY_THRESHOLD = 0.58;
export const FLOWBUILDER_LOW_ZOOM_EDGE_CAP = 140;
export const FLOWBUILDER_LOW_ZOOM_COMPLEXITY_THRESHOLD = 450;
export const FLOWBUILDER_SIDEBAR_DEFERRED_MOUNT_MS = 120;
export const FLOWBUILDER_INTERACTION_EDGE_CAP = 180;
export const FLOWBUILDER_INTERACTION_EDGE_COMPLEXITY_THRESHOLD = 550;
export const FLOWBUILDER_ZOOM_STEP = 0.08;
export const FLOWBUILDER_ZOOM_ANIMATION_MS = 120;
