import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import type { ConsentForm } from "@/features/treatments/types";

interface ConsentDetailModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  consent?: ConsentForm;
  onEdit: (id: string) => void;
}

export function ConsentDetailModal({ open, onOpenChange, consent, onEdit }: ConsentDetailModalProps) {
  if (!consent) return null;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[620px] bg-slate-50 overflow-hidden flex flex-col p-0 max-h-[85vh]">
        <DialogHeader className="px-6 py-5 border-b border-slate-200 bg-white shrink-0">
          <DialogTitle className="text-xl font-bold text-slate-900">
            {consent.name}
          </DialogTitle>
          <p className="text-sm text-slate-500 mt-1">Consent details</p>
        </DialogHeader>

        <div className="flex-1 overflow-y-auto p-6 bg-white space-y-6">
          <div className="flex gap-4 mb-4">
            <div className="px-3 py-1.5 rounded-md border border-slate-200 bg-slate-50 text-sm font-medium text-slate-700">
              <span className="text-slate-400 mr-2 text-xs uppercase tracking-wider">Scope</span>
              {consent.scope}
            </div>
            {consent.visitTypeKeys.length > 0 && (
              <div className="px-3 py-1.5 rounded-md border border-slate-200 bg-slate-50 text-sm font-medium text-slate-700">
                <span className="text-slate-400 mr-2 text-xs uppercase tracking-wider">Visit Types</span>
                {consent.visitTypeKeys.join(", ")}
              </div>
            )}
          </div>

          <div className="border border-slate-200 rounded-lg overflow-hidden">
            <div className="bg-slate-50 border-b border-slate-200 px-4 py-2">
              <span className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Consent Text Preview</span>
            </div>
            <div className="p-5 text-sm text-slate-700 leading-relaxed bg-white prose prose-sm max-w-none">
              <p>This is a placeholder for the rich text consent content.</p>
              <p>In a real implementation, this would render HTML generated by the rich text editor.</p>
            </div>
          </div>
        </div>

        <div className="px-6 py-4 border-t border-slate-200 bg-slate-50 shrink-0 flex justify-end gap-2">
          <Button variant="outline" onClick={() => onOpenChange(false)}>Close</Button>
          <Button className="bg-[#12517A] text-white hover:bg-[#12517A]/90" onClick={() => {
            onOpenChange(false);
            onEdit(consent.id);
          }}>
            Edit Consent
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
